### PR TITLE
Use vendored openssl on Android

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Comment by teawithsand** [comment]
I am going to research possibility of using other library than OpenSSL first, preferably rust-only, in fact OpenSSL is used only for
1. Generating RSA keys
2. Serializing public/secret RSA keys
3. Deserializing public/secret RSA keys

In fact, OpenSSL is doing much more, so it may not be best suited library for this purpose.
Also, approach where tor generates key is NIY.

There should be library(libraries?) doing all of above.
In fact formats used right now are pretty standard, so it should even preserve backwards-serialization compatibility.

If do not find any lib I will merge this, otherwise I will implement it and add some tests for backwards-compatibility.

**Comment by dr-orlovsky** [comment]
Can you pls merge this; I tried to do RSA migration https://github.com/teawithsand/torut/pull/6 and got blocked for now

**Comment by teawithsand** [comment]
I've added vendored_openssl feature in 0.1.6 It should do AFAIK.
This should be kind of middle ground until I figure out how to implement it with rsa crate properly(as it should be).

**Comment by dr-orlovsky** [comment]
Closed by https://github.com/teawithsand/torut/commit/0f5cc03798aeeeb523ea33e69dde6623f96c99d8

**Pull request closed without merging**
